#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Let me just clean that up real quick..."

# git diff --name-only --cached

OUTPUT=$(git diff --name-only --cached)
echo "${OUTPUT}"

exit 1

yarn prettier --write src/*
