name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-20.04
    outputs:
      next-version: ${{ steps.package_version.output.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Get Package Version
        run: |
           echo "::set-output name=version::$(node -pe "require('./package.json').version")\n"
        id: package_version
      
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          issuesWoLabels: false
          prWoLabels: false
          excludeLabels: duplicate,question,invalid,wontfix,maintenance,release
          futureRelease: '${{steps.package_version.output.version}}'
#           token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Commit Changelog
        run: |
          git add .
          git commit -m 'chore: generate changelog for version ${{steps.package_version.output.version}}'
          git push
          
  open-pr:
    needs: publish-release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
          
      - name: Reset release branch
        run: |
          git fetch origin ${{steps.extract_branch.branch}}:${{steps.extract_branch.branch}}
          git reset --hard ${{steps.extract_branch.branch}}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          commit-message: 'chore: release version ${{jobs.publish-release.next-version}}'
          committer: GitHub Actions Bot <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: '${{steps.extract_branch.branch}}'
          delete-branch: true
          title: 'Chore: release version ${{jobs.publish-release.next-version}}'
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: release
